FROM python:3.7.3-alpine3.9 as prod

RUN mkdir /app/
WORKDIR /app/

COPY ./api/requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY ./api/ /app/

ENV FLASK_APP=server.py
CMD flask run -h 0.0.0 -p 23333
